### ISSUE TITLE
Use it for get data from mic and to play back audio

### ISSUE THREAD

**Issue by fborot** [edimuj/cordova-plugin-audioinput#37] opened 2017-02-10 14:07 UTC
Hi, nice promising plugin, thank you

Is it possible to use this plugin to do these 2 things at the same time:? 

1- get data from mic, use the events mode , for example: get the data from the buffer, copy it to my local buffer and prepare/process the bytes to be sent to the network for a remote end to receive and playback.

2- playback back audio that I obtain from another buffer at the same time : I receive bytes from the network , put them in a buffer and I want to playback the audio from the buffer without interrupting the collection of bytes from the mic described in step 1

I have been able to do step 1 above on Android to get data from the microphone and send it to the network very close to real time, very small latency. Now I need to play back (at the same time) data that I obtain from the network (I am making a VoIP app). using the events mode . How can I use this plugin to also playback the audio I get form the remote end ?

Is the same functionality available for iOS ? When I try my app on iOS (step1) the audio sounds very bad, and very choppy. 
Please advise

**Comment by edimuj** [comment] 2017-03-18 11:25
This plugin is, as the name implies, built for audioinput only. I see no problem with playing sound using, for example, the Web Audio API regardless if the sound data comes from a server or the local device microphone. Regarding the choppy sound on iOS, I cannot reproduce that here, do you have a project that I can look at in order to understand better?

**Comment by edimuj** [comment] 2017-06-07 11:43
Closing this issue, since there haven't been any activity for a while. Just give me a shout, if you want it to be reopened.

**Closed by edimuj** 2017-06-07 11:43 UTC
Labels: question
