### ISSUE TITLE
uncaught reference error: Console message is not defined

### ISSUE THREAD

**Issue by NickLusson** [edimuj/cordova-plugin-audioinput#78] opened 2018-10-02 06:56 UTC
Hi,.. Thanks for this..

When i use the code as you have provided.. when running the code it always displays "Not Ready".

In the debugger it says:
wav-demo.js:173 Uncaught ReferenceError: consoleMessage is not defined
    at onDeviceReady (wav-demo.js:173)
    at wav-demo.js:182

**Comment by NickLusson** [comment] 2018-10-02 09:29
when i remove the plugin and add it again it says:

Plugin doesn't support this project's cordova-android version. cordova-android: 7.1.1, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android

**Comment by edimuj** [comment] 2018-11-25 02:30
The "cordova-android: 7.1.1" is not an error message. It only indicates that the cordova-plugin-compat plugin isn't needed and won't be installed along with this plugin.

As for your other issue, I don't really know why this happens, since it isn't something that I can reproduce. Do you have a project I can look at perhaps?

**Comment by edimuj** [comment] 2019-01-09 10:20
Since there haven't been any activity on this issue for some months now, I'm closing it. Feel free to open it again if there is any change or new information.

**Closed by edimuj** 2019-01-09 10:20 UTC
